pool:
  vmImage: 'ubuntu-latest'

name: "$(Rev:r)"
variables:
  - name: MajorMinor
    value: '3.3'
  - name: ProductVersion
    ${{ if eq(variables['Build.SourceBranchName'], 'release') }}:
      value: 'MyProduct-$(MajorMinor)'
    ${{ else }}:
      value: 'MyProduct-$(MajorMinor)-beta-$(Build.BuildNumber)'

stages:
- stage: ci
  displayName: Continuous Integration
  jobs:
  - job: build
    displayName: 'Build and Publish Weather Forecast API'
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK 8.x'
      inputs:
        version: '8.x'

    - task: DotNetCoreCLI@2
      displayName: 'Compile the application'
      inputs:
        projects: '**/*.csproj'
        arguments: '--configuration $(configuration)'

    - task: DotNetCoreCLI@2
      displayName: 'Run unit tests'
      inputs:
        command: test
        projects: '**/*.UnitTests.csproj'
        arguments: '--configuration $(configuration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'
        publishTestResults: true

    - task: DotNetCoreCLI@2
      displayName: 'Run integration tests'
      inputs:
        command: test
        projects: '**/*.IntegrationTests.csproj'
        publishTestResults: true
        arguments: '--configuration $(configuration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'

    - task: PublishCodeCoverageResults@2
      displayName: 'Publish Coverage to ADO'
      inputs:
        summaryFileLocation: '**/*coverage.cobertura.xml'
        codeCoverageTool: 'cobertura'

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet Publish'
      inputs:
        command: publish
        arguments: '--output $(Build.ArtifactStagingDirectory)/api-package --configuration $(configuration)'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifact'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/api-package'
        artifact: 'WeatherForecastApi'



- stage: cd
  displayName: Continuous Deployment
  dependsOn: ci
  condition: succeeded()
  jobs:
  - template: stage-deployment.yml
    parameters:
      ResourceGroupName: 'MyResourceGroup'
      WebAppName: 'ijwebappdotnet'

# just to test build number ID
#- stage: demo
#  jobs:
#    - job: demo_job
#      steps:
#        - script: echo $(ProductVersion)
#          displayName: 'Display Product Version'

