name: Build Weather Forecast API

on:
  push:
    branches: ['master']

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Dot Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Dotnet Test
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Publish
        run: dotnet publish --configuration Release --output ./api-package --no-build

      - name: Create Zip file
        run: zip -r api-package.zip . -i api-package/*

      - name: Publish Zip file
        uses: actions/upload-artifact@v4
        with:
          name: ZipDeployFile
          path: api-package.zip
# packaging client files now
      - name: Pack Nugget Client Package
        run: dotnet pack WeatherForecast.Client/WeatherForecast.Client.csproj --configuration Release --output packages -p:Version=1.2.3

      # packaging files now
      - name: Pack Nugget API Dto Package
        run: dotnet pack WeatherForecast.Api.Dto/WeatherForecast.Api.Dto.csproj --configuration Release --output packages -p:Version=1.2.3

# publish nuget package
      - name: Publish Nuget Client Package
        run: dotnet nuget push packages/WeatherForecast.Client*.nupkg --source 'https://nuget.pkg.github.com/freejeomi/index.json' --api-key ${{ secrets.GIT_PAT_TOKEN }}

      # publish nuget package
      - name: Publish Nuget Client Package
        run: dotnet nuget push packages/WeatherForecast.Api.Dto*.nupkg --source 'https://nuget.pkg.github.com/freejeomi/index.json' --api-key ${{ secrets.GIT_PAT_TOKEN }}


# will deploy later
#  Deploy:
#    needs: Build
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/download-artifact@v4
#        name: ZipDeployFile
#
#      - name: Login to Azure
#        uses: azure/login@v1
#        with:
#          creds: ${{ secrets.AZURE_CREDENTIALS }}
#
#      - name: Deploy to Azure Web App Prod
#        uses: azure/webapps-deploy@v2
#        with:
#          app-name: 'ijwebappdotnet-prod'
#          package: 'ZipDeployFile/api-package.zip'
